[project]
name = "3d-gaussian-splatting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastplotlib>=0.5.0",
    "glfw>=2.9.0",
    "jax",
    "jaxlib",
    "jax-cuda12-plugin[with-cuda]",
    "jax-cuda12-pjrt",
    "pycolmap>=3.11.1",
]

[tool.uv.sources]
jax = { index = "jax-nightly" }
jaxlib = { index = "jax-nightly" }
jax-cuda12-plugin = { index = "jax-nightly" }
jax-cuda12-pjrt = { index = "jax-nightly" }

[[tool.uv.index]]
name = "jax-nightly"
url = "https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/"
explicit = true

[tool.uv]
prerelease = "allow"
[tool.ruff]
exclude = [".mypy_cache", ".venv"]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D213",
    "D415",
    "COM812",
    "T201",
    "ERA001",
    "PLR0913",
    "N802",
    "N803",
    "N806",
    "RUF002",
    "RUF003",
]

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
include = ["src", "."]
pythonVersion = "3.12"
typeCheckingMode = "standard"
